// Card images are shown as small thumbnails and only load the full-size image
// when opened (lightbox) or when the card navigates to a detail page.
//
// Thumbnails live in a `Thumbnails/` folder beside the original, with the same
// filename, generated by scripts/generate-thumbnails.mjs:
//
//   /compendium/Adventures/X/Culexis.jpg
//   → /compendium/Adventures/X/Thumbnails/Culexis.jpg

export function thumbSrc(src) {
  if (!src) return src;
  const slash = src.lastIndexOf("/");
  if (slash === -1) return "Thumbnails/" + src;
  return src.slice(0, slash + 1) + "Thumbnails/" + src.slice(slash + 1);
}

// onError handler for a card <img>: if the thumbnail is missing, fall back to
// the full-size image once so the card never shows a broken picture.
export function onThumbError(fullSrc) {
  return (e) => {
    const img = e.currentTarget;
    if (img.dataset.fullFallback || !fullSrc) return;
    img.dataset.fullFallback = "1";
    img.src = fullSrc;
  };
}
