// Scans every .md file under reference/ and writes reader-data.js, which the
// bundled index.html reads to show all the source documents in a nice layout.
//
// Run it whenever the .md files change:
//
//   node reference/build-reader.mjs
//
// Then open reference/index.html in a browser (no server needed).

import { readdirSync, readFileSync, writeFileSync, statSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.dirname(fileURLToPath(import.meta.url));

// Recursively collect every .md under reference/ (skip this tool's own files).
function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (name.toLowerCase().endsWith(".md")) out.push(full);
  }
  return out;
}

// First "# Heading" in the file, else a title-cased filename.
function titleOf(body, file) {
  const m = body.match(/^\s*#\s+(.+?)\s*$/m);
  if (m) return m[1].replace(/\s*[—–-]\s*(GM Summary.*|Spelledarsammanfattning.*|Summary.*).*$/i, "").trim();
  return path
    .basename(file, ".md")
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const FOLDER_LABELS = {
  adventures: "Adventures",
  bestiary: "Bestiary",
  handbooks: "Handbooks",
  peoples: "Peoples",
  sourcebooks: "Sourcebooks",
  "": "Other",
};

const files = walk(ROOT).sort();
const docs = files.map((full) => {
  const rel = path.relative(ROOT, full).split(path.sep).join("/");
  const folder = rel.includes("/") ? rel.split("/")[0] : "";
  const body = readFileSync(full, "utf8");
  return {
    path: rel,
    folder: FOLDER_LABELS[folder] ?? folder,
    title: titleOf(body, full),
    body,
  };
});

const out =
  "// AUTO-GENERATED by build-reader.mjs - do not edit by hand.\n" +
  "window.MD_DOCS = " +
  JSON.stringify(docs, null, 0) +
  ";\n";

writeFileSync(path.join(ROOT, "reader-data.js"), out);
console.log(`Wrote reader-data.js with ${docs.length} documents.`);
